// Regenerates src/default-links.ts from links.toml (the embedded copy keeps pure
// code and tests working without a file read; test/unit/link-rules.spec.ts fails on drift).
import { readFileSync, writeFileSync } from 'node:fs'

const text = readFileSync(new URL('../links.toml', import.meta.url), 'utf8')
writeFileSync(
  new URL('../src/default-links.ts', import.meta.url),
  `// Generated by scripts/default-links.mjs from links.toml. Do not edit.\nexport const DEFAULT_LINKS_TOML: string = ${JSON.stringify(text)}\n`,
)
