// Dev-only: bundle a subset of graphql-js into src/vendor/graphql.js for the
// mod sandbox (no Node, no require, no dynamic import, no process, < 1 MiB).
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outfile = join(root, 'src/vendor/graphql.js');
const version = JSON.parse(readFileSync(join(root, 'node_modules/graphql/package.json'), 'utf8')).version;

await build({
  entryPoints: [join(root, 'scripts/graphql-entry.mjs')],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  mainFields: ['module', 'main'],
  target: 'es2022',
  minify: false,
  legalComments: 'inline',
  treeShaking: true,
  // graphql-js decides production mode with
  //   globalThis.process && process.env.NODE_ENV === 'production'
  // Replacing `globalThis.process` with `true` (not `undefined`) turns that into
  // `true && "production" === "production"`, selecting the plain `instanceof`
  // path, and leaves no `process` reference in the output.
  define: {
    'process.env.NODE_ENV': '"production"',
    'globalThis.process': 'true',
  },
  banner: {
    js: `// Vendored graphql-js ${version} subset (parse, visit, print, Kind, BREAK, OperationTypeNode).\n// Generated by scripts/vendor.mjs; do not edit. MIT License, Copyright (c) GraphQL Contributors.`,
  },
  logLevel: 'warning',
});

const text = readFileSync(outfile, 'utf8');
const size = Buffer.byteLength(text, 'utf8');
const LIMIT = 1024 * 1024;
const forbidden = ['import(', 'require(', 'process.', 'eval(', 'new Function'];
const problems = [];
if (size >= LIMIT) problems.push(`size ${size} bytes is >= 1 MiB`);
for (const f of forbidden) {
  const i = text.indexOf(f);
  if (i !== -1) problems.push(`contains ${JSON.stringify(f)} near: ${JSON.stringify(text.slice(Math.max(0, i - 60), i + 40))}`);
}
// Any bare `process` identifier is also suspect.
if (/\bprocess\b/.test(text)) problems.push('contains identifier "process"');

console.log(`src/vendor/graphql.js: ${size} bytes (${(size / 1024).toFixed(1)} KiB), graphql ${version}`);
if (problems.length) {
  for (const p of problems) console.error(`FAIL: ${p}`);
  process.exit(1);
}
console.log('OK: no forbidden constructs');
