// Emoji shortcodes drawn as the emoji they name. Pure: no $.
//
// Text from Slack, GitHub, Jira and incident.io bots carries shortcodes such
// as `:fire:` or `:large_green_circle:`; the pane shows the emoji instead.
// Only names in EMOJI are replaced. Anything else is left exactly as it came:
// a custom image Slack cannot send as text (`:slack:`), a name this table does
// not know, and text that merely looks like a shortcode (`10:30:45`,
// `std::fire::x`).
//
// Draw the result after escaping text (see escape.ts), not before: ZWJ
// sequences such as the firefighters contain U+200D (zero-width joiner), which
// escaping turns into a visible escape.

/** The longest name looked for; real names are under 40 characters. */
const NAME_MAX = 64

/** `[a-z0-9_+-]`, as Slack writes names (case-sensitive). */
const isNameChar = (code: number) =>
  (code >= 97 && code <= 122) || (code >= 48 && code <= 57) || code === 95 || code === 43 || code === 45

/** `[A-Za-z0-9_]`; NaN, past either end of the text, is not. */
const isWordChar = (code: number) =>
  (code >= 97 && code <= 122) || (code >= 65 && code <= 90) || (code >= 48 && code <= 57) || code === 95

const COLON = 58
/** `:skin-tone-2:` to `:skin-tone-6:` follow a base emoji: 2 is U+1F3FB, 6 is U+1F3FF. */
const SKIN_TONE = ':skin-tone-'
const SKIN_TONE_LENGTH = SKIN_TONE.length + 2

// Built lazily and guarded: a runtime without Unicode property escapes then
// leaves tones as their own swatch emoji instead of failing to load.
let modifiable: RegExp | null | undefined
const canTakeTone = (char: string): boolean => {
  if (modifiable === undefined) {
    try {
      modifiable = new RegExp('\\p{Emoji_Modifier_Base}', 'u')
    } catch {
      modifiable = null
    }
  }
  return modifiable !== null && modifiable.test(char)
}

/**
 * `base` with a skin tone: the modifier follows the first emoji that takes
 * one, ahead of any ZWJ (woman firefighter, medium tone: woman, tone, ZWJ,
 * fire engine), replacing U+FE0F. Null when nothing in `base` takes a tone.
 */
function withTone(base: string, tone: string): string | null {
  let at = 0
  for (const char of base) {
    at += char.length
    if (!canTakeTone(char)) continue
    const rest = base.slice(at)
    return base.slice(0, at) + tone + (rest.startsWith('\u{FE0F}') ? rest.slice(1) : rest)
  }
  return null
}

/**
 * Replaces `:name:` with its emoji when `name` is in EMOJI, and `:name::skin-tone-N:`
 * with the emoji in that tone. Linear in the length of `text`; returns `text`
 * itself when nothing changed, and never throws.
 */
export function emojify(text: string): string {
  try {
    let out = ''
    let copied = 0 // text before this index is in `out` or unchanged
    let tokenEnd = -1 // just past the last well-formed `:name:`
    let open = text.indexOf(':')
    while (open !== -1) {
      let close = open + 1
      while (close < text.length && close - open <= NAME_MAX && isNameChar(text.charCodeAt(close))) close++
      if (close === open + 1 || text.charCodeAt(close) !== COLON) {
        open = text.indexOf(':', open + 1)
        continue
      }
      // `:name:` is whole: a hit, or at least one token. A colon straight
      // after it opens the next token (`:fire::fire:`).
      const name = text.slice(open + 1, close)
      let end = close + 1
      const afterColon = open > 0 && text.charCodeAt(open - 1) === COLON && open !== tokenEnd // `a::fire::b`
      const insideWord = isWordChar(text.charCodeAt(open - 1)) && isWordChar(text.charCodeAt(end)) // `10:30:45`, `a:x:c`
      tokenEnd = end
      let emoji = !afterColon && !insideWord && Object.hasOwn(EMOJI, name) ? EMOJI[name] : undefined
      if (emoji !== undefined && text.startsWith(SKIN_TONE, end) && text.charCodeAt(end + SKIN_TONE_LENGTH - 1) === COLON) {
        const level = text.charCodeAt(end + SKIN_TONE.length) - 48
        const toned = level >= 2 && level <= 6 ? withTone(emoji, String.fromCodePoint(0x1f3fb + level - 2)) : null
        if (toned !== null) {
          emoji = toned
          end += SKIN_TONE_LENGTH
          tokenEnd = end
        }
      }
      if (emoji !== undefined) {
        out += text.slice(copied, open) + emoji
        copied = end
      }
      open = text.indexOf(':', end)
    }
    return copied === 0 ? text : out + text.slice(copied)
  } catch {
    return text
  }
}

/**
 * Shortcode name (no colons) to emoji, in emoji presentation (U+FE0F where the
 * base character would default to text). Slack's names and GitHub's both,
 * where they differ (`thumbsup` and `+1`, `large_green_circle` and
 * `green_circle`). Where they name different emoji, Slack's wins
 * (`satellite` is the satellite, `satellite_antenna` the dish).
 */
export const EMOJI: Readonly<Record<string, string>> = Object.freeze({
  // smileys
  grinning: '😀',
  smiley: '😃',
  smile: '😄',
  grin: '😁',
  laughing: '😆',
  satisfied: '😆',
  sweat_smile: '😅',
  rolling_on_the_floor_laughing: '🤣',
  rofl: '🤣',
  joy: '😂',
  slightly_smiling_face: '🙂',
  simple_smile: '🙂',
  upside_down_face: '🙃',
  wink: '😉',
  blush: '😊',
  innocent: '😇',
  smiling_face_with_3_hearts: '🥰',
  heart_eyes: '😍',
  'star-struck': '🤩',
  star_struck: '🤩',
  kissing_heart: '😘',
  kissing: '😗',
  relaxed: '☺️',
  smiling_face_with_tear: '🥲',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  money_mouth_face: '🤑',
  hugging_face: '🤗',
  hugs: '🤗',
  face_with_hand_over_mouth: '🤭',
  shushing_face: '🤫',
  thinking_face: '🤔',
  thinking: '🤔',
  zipper_mouth_face: '🤐',
  face_with_raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  smirk: '😏',
  unamused: '😒',
  face_with_rolling_eyes: '🙄',
  roll_eyes: '🙄',
  grimacing: '😬',
  relieved: '😌',
  pensive: '😔',
  sleepy: '😪',
  sleeping: '😴',
  mask: '😷',
  face_with_thermometer: '🤒',
  face_with_head_bandage: '🤕',
  nauseated_face: '🤢',
  face_vomiting: '🤮',
  hot_face: '🥵',
  partying_face: '🥳',
  sunglasses: '😎',
  nerd_face: '🤓',
  face_with_monocle: '🧐',
  confused: '😕',
  worried: '😟',
  slightly_frowning_face: '🙁',
  white_frowning_face: '☹️',
  open_mouth: '😮',
  astonished: '😲',
  flushed: '😳',
  pleading_face: '🥺',
  frowning: '😦',
  fearful: '😨',
  cold_sweat: '😰',
  cry: '😢',
  sob: '😭',
  scream: '😱',
  disappointed: '😞',
  sweat: '😓',
  weary: '😩',
  tired_face: '😫',
  yawning_face: '🥱',
  rage: '😡',
  angry: '😠',
  face_with_symbols_on_mouth: '🤬',
  imp: '👿',
  skull: '💀',
  skull_and_crossbones: '☠️',
  hankey: '💩',
  poop: '💩',
  ghost: '👻',
  alien: '👽',
  robot_face: '🤖',
  robot: '🤖',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  melting_face: '🫠',
  saluting_face: '🫡',
  face_holding_back_tears: '🥹',
  // hearts and feelings
  kiss: '💋',
  cupid: '💘',
  sparkling_heart: '💖',
  heartbeat: '💓',
  two_hearts: '💕',
  broken_heart: '💔',
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  brown_heart: '🤎',
  black_heart: '🖤',
  white_heart: '🤍',
  pink_heart: '🩷',
  '100': '💯',
  anger: '💢',
  boom: '💥',
  collision: '💥',
  dizzy: '💫',
  sweat_drops: '💦',
  dash: '💨',
  bomb: '💣',
  zzz: '💤',
  // speech
  speech_balloon: '💬',
  thought_balloon: '💭',
  // hands and body
  wave: '👋',
  raised_hand_with_fingers_splayed: '🖐️',
  hand: '✋',
  raised_hand: '✋',
  'spock-hand': '🖖',
  ok_hand: '👌',
  v: '✌️',
  crossed_fingers: '🤞',
  i_love_you_hand_sign: '🤟',
  the_horns: '🤘',
  point_left: '👈',
  point_right: '👉',
  point_up_2: '👆',
  point_down: '👇',
  point_up: '☝️',
  middle_finger: '🖕',
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  fist: '✊',
  facepunch: '👊',
  clap: '👏',
  raised_hands: '🙌',
  handshake: '🤝',
  pray: '🙏',
  muscle: '💪',
  brain: '🧠',
  eyes: '👀',
  eye: '👁️',
  tongue: '👅',
  lips: '👄',
  'skin-tone-2': '🏻',
  'skin-tone-3': '🏼',
  'skin-tone-4': '🏽',
  'skin-tone-5': '🏾',
  'skin-tone-6': '🏿',
  // people
  bust_in_silhouette: '👤',
  busts_in_silhouette: '👥',
  speaking_head_in_silhouette: '🗣️',
  footprints: '👣',
  man: '👨',
  woman: '👩',
  'male-firefighter': '👨‍🚒',
  'female-firefighter': '👩‍🚒',
  firefighter: '🧑‍🚒',
  man_firefighter: '👨‍🚒',
  woman_firefighter: '👩‍🚒',
  'male-technologist': '👨‍💻',
  'female-technologist': '👩‍💻',
  technologist: '🧑‍💻',
  'male-doctor': '👨‍⚕️',
  'female-doctor': '👩‍⚕️',
  health_worker: '🧑‍⚕️',
  'male-scientist': '👨‍🔬',
  'female-scientist': '👩‍🔬',
  scientist: '🧑‍🔬',
  'male-police-officer': '👮‍♂️',
  'female-police-officer': '👮‍♀️',
  cop: '👮',
  construction_worker: '👷',
  sleuth_or_spy: '🕵️',
  bow: '🙇',
  face_palm: '🤦',
  facepalm: '🤦',
  'man-facepalming': '🤦‍♂️',
  'woman-facepalming': '🤦‍♀️',
  shrug: '🤷',
  'man-shrugging': '🤷‍♂️',
  'woman-shrugging': '🤷‍♀️',
  raising_hand: '🙋',
  no_good: '🙅',
  runner: '🏃',
  running: '🏃',
  'man-running': '🏃‍♂️',
  'woman-running': '🏃‍♀️',
  // animals
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  hamster: '🐹',
  rabbit: '🐰',
  fox_face: '🦊',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  duck: '🦆',
  unicorn_face: '🦄',
  honeybee: '🐝',
  bee: '🐝',
  bug: '🐛',
  butterfly: '🦋',
  snail: '🐌',
  ant: '🐜',
  spider: '🕷️',
  turtle: '🐢',
  snake: '🐍',
  octopus: '🐙',
  shrimp: '🦐',
  crab: '🦀',
  fish: '🐟',
  tropical_fish: '🐠',
  dolphin: '🐬',
  whale: '🐳',
  shark: '🦈',
  dragon: '🐉',
  paw_prints: '🐾',
  // plants and nature
  bouquet: '💐',
  cherry_blossom: '🌸',
  rose: '🌹',
  seedling: '🌱',
  evergreen_tree: '🌲',
  deciduous_tree: '🌳',
  palm_tree: '🌴',
  shamrock: '☘️',
  four_leaf_clover: '🍀',
  maple_leaf: '🍁',
  fallen_leaf: '🍂',
  leaves: '🍃',
  earth_africa: '🌍',
  earth_americas: '🌎',
  earth_asia: '🌏',
  globe_with_meridians: '🌐',
  mountain: '⛰️',
  volcano: '🌋',
  ocean: '🌊',
  // weather and sky
  sunny: '☀️',
  partly_sunny: '⛅',
  cloud: '☁️',
  rain_cloud: '🌧️',
  cloud_with_rain: '🌧️',
  snow_cloud: '🌨️',
  cloud_with_snow: '🌨️',
  lightning: '🌩️',
  cloud_with_lightning: '🌩️',
  tornado: '🌪️',
  fog: '🌫️',
  rainbow: '🌈',
  umbrella: '☔',
  snowflake: '❄️',
  snowman: '⛄',
  zap: '⚡',
  fire: '🔥',
  droplet: '💧',
  star: '⭐',
  star2: '🌟',
  sparkles: '✨',
  moon: '🌔',
  full_moon: '🌕',
  crescent_moon: '🌙',
  thermometer: '🌡️',
  // food and drink
  apple: '🍎',
  banana: '🍌',
  watermelon: '🍉',
  grapes: '🍇',
  strawberry: '🍓',
  bread: '🍞',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  taco: '🌮',
  egg: '🥚',
  cheese_wedge: '🧀',
  cookie: '🍪',
  cake: '🍰',
  birthday: '🎂',
  chocolate_bar: '🍫',
  candy: '🍬',
  icecream: '🍦',
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  wine_glass: '🍷',
  cocktail: '🍸',
  champagne: '🍾',
  clinking_glasses: '🥂',
  sushi: '🍣',
  fork_and_knife: '🍴',
  spoon: '🥄',
  knife: '🔪',
  // celebration and games
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  gift: '🎁',
  fireworks: '🎆',
  trophy: '🏆',
  sports_medal: '🏅',
  first_place_medal: '🥇',
  '1st_place_medal': '🥇',
  second_place_medal: '🥈',
  '2nd_place_medal': '🥈',
  third_place_medal: '🥉',
  '3rd_place_medal': '🥉',
  soccer: '⚽',
  basketball: '🏀',
  football: '🏈',
  baseball: '⚾',
  tennis: '🎾',
  golf: '⛳',
  dart: '🎯',
  video_game: '🎮',
  spades: '♠️',
  hearts: '♥️',
  diamonds: '♦️',
  clubs: '♣️',
  // office and tools
  computer: '💻',
  desktop_computer: '🖥️',
  keyboard: '⌨️',
  printer: '🖨️',
  iphone: '📱',
  phone: '☎️',
  telephone: '☎️',
  telephone_receiver: '📞',
  pager: '📟',
  battery: '🔋',
  camera: '📷',
  mag: '🔍',
  mag_right: '🔎',
  bulb: '💡',
  flashlight: '🔦',
  candle: '🕯️',
  book: '📖',
  books: '📚',
  notebook: '📓',
  page_facing_up: '📄',
  newspaper: '📰',
  bookmark: '🔖',
  moneybag: '💰',
  dollar: '💵',
  credit_card: '💳',
  receipt: '🧾',
  chart: '💹',
  email: '✉️',
  envelope: '✉️',
  'e-mail': '📧',
  incoming_envelope: '📨',
  envelope_with_arrow: '📩',
  outbox_tray: '📤',
  inbox_tray: '📥',
  package: '📦',
  mailbox: '📫',
  pencil2: '✏️',
  pencil: '📝',
  memo: '📝',
  pen: '🖊️',
  briefcase: '💼',
  file_folder: '📁',
  open_file_folder: '📂',
  date: '📅',
  calendar: '📆',
  spiral_note_pad: '🗒️',
  spiral_notepad: '🗒️',
  spiral_calendar_pad: '🗓️',
  spiral_calendar: '🗓️',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  clipboard: '📋',
  pushpin: '📌',
  round_pushpin: '📍',
  paperclip: '📎',
  linked_paperclips: '🖇️',
  scissors: '✂️',
  wastebasket: '🗑️',
  lock: '🔒',
  unlock: '🔓',
  closed_lock_with_key: '🔐',
  key: '🔑',
  hammer: '🔨',
  hammer_and_wrench: '🛠️',
  shield: '🛡️',
  wrench: '🔧',
  nut_and_bolt: '🔩',
  gear: '⚙️',
  scales: '⚖️',
  link: '🔗',
  toolbox: '🧰',
  magnet: '🧲',
  microscope: '🔬',
  telescope: '🔭',
  satellite_antenna: '📡',
  satellite: '🛰️',
  fire_extinguisher: '🧯',
  shopping_cart: '🛒',
  thread: '🧵',
  crown: '👑',
  gem: '💎',
  bell: '🔔',
  no_bell: '🔕',
  loudspeaker: '📢',
  mega: '📣',
  mute: '🔇',
  speaker: '🔈',
  sound: '🔉',
  loud_sound: '🔊',
  musical_note: '🎵',
  notes: '🎶',
  microphone: '🎤',
  headphones: '🎧',
  control_knobs: '🎛️',
  // time
  hourglass: '⌛',
  hourglass_flowing_sand: '⏳',
  watch: '⌚',
  alarm_clock: '⏰',
  stopwatch: '⏱️',
  timer_clock: '⏲️',
  clock1: '🕐',
  clock2: '🕑',
  clock3: '🕒',
  clock4: '🕓',
  clock5: '🕔',
  clock6: '🕕',
  clock7: '🕖',
  clock8: '🕗',
  clock9: '🕘',
  clock10: '🕙',
  clock11: '🕚',
  clock12: '🕛',
  // travel and places
  rocket: '🚀',
  airplane: '✈️',
  helicopter: '🚁',
  car: '🚗',
  red_car: '🚗',
  bus: '🚌',
  truck: '🚚',
  ambulance: '🚑',
  fire_engine: '🚒',
  police_car: '🚓',
  bike: '🚲',
  train: '🚋',
  ship: '🚢',
  anchor: '⚓',
  boat: '⛵',
  sailboat: '⛵',
  rotating_light: '🚨',
  construction: '🚧',
  fuelpump: '⛽',
  traffic_light: '🚥',
  vertical_traffic_light: '🚦',
  octagonal_sign: '🛑',
  stop_sign: '🛑',
  flying_saucer: '🛸',
  house: '🏠',
  office: '🏢',
  hospital: '🏥',
  bank: '🏦',
  factory: '🏭',
  // signs and symbols
  warning: '⚠️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  no_smoking: '🚭',
  radioactive_sign: '☢️',
  radioactive: '☢️',
  biohazard_sign: '☣️',
  biohazard: '☣️',
  recycle: '♻️',
  arrow_up: '⬆️',
  arrow_upper_right: '↗️',
  arrow_right: '➡️',
  arrow_lower_right: '↘️',
  arrow_down: '⬇️',
  arrow_lower_left: '↙️',
  arrow_left: '⬅️',
  arrow_upper_left: '↖️',
  arrow_up_down: '↕️',
  left_right_arrow: '↔️',
  arrows_clockwise: '🔃',
  arrows_counterclockwise: '🔄',
  back: '🔙',
  end: '🔚',
  on: '🔛',
  soon: '🔜',
  top: '🔝',
  repeat: '🔁',
  arrow_forward: '▶️',
  fast_forward: '⏩',
  rewind: '⏪',
  arrow_backward: '◀️',
  arrow_up_small: '🔼',
  arrow_double_up: '⏫',
  arrow_down_small: '🔽',
  arrow_double_down: '⏬',
  infinity: '♾️',
  white_check_mark: '✅',
  ballot_box_with_check: '☑️',
  heavy_check_mark: '✔️',
  heavy_multiplication_x: '✖️',
  x: '❌',
  negative_squared_cross_mark: '❎',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  sparkle: '❇️',
  bangbang: '‼️',
  double_exclamation_mark: '‼️',
  interrobang: '⁉️',
  question: '❓',
  grey_question: '❔',
  grey_exclamation: '❕',
  exclamation: '❗',
  heavy_exclamation_mark: '❗',
  copyright: '©️',
  registered: '®️',
  tm: '™️',
  information_source: 'ℹ️',
  hash: '#️⃣',
  keycap_star: '*️⃣',
  asterisk: '*️⃣',
  zero: '0️⃣',
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  ok: '🆗',
  new: '🆕',
  sos: '🆘',
  up: '🆙',
  cool: '🆒',
  id: '🆔',
  red_circle: '🔴',
  orange_circle: '🟠',
  large_orange_circle: '🟠',
  yellow_circle: '🟡',
  large_yellow_circle: '🟡',
  green_circle: '🟢',
  large_green_circle: '🟢',
  blue_circle: '🔵',
  large_blue_circle: '🔵',
  purple_circle: '🟣',
  large_purple_circle: '🟣',
  brown_circle: '🟤',
  large_brown_circle: '🟤',
  black_circle: '⚫',
  white_circle: '⚪',
  large_red_square: '🟥',
  large_orange_square: '🟧',
  large_yellow_square: '🟨',
  large_green_square: '🟩',
  large_blue_square: '🟦',
  large_purple_square: '🟪',
  large_brown_square: '🟫',
  black_large_square: '⬛',
  white_large_square: '⬜',
  // flags
  triangular_flag_on_post: '🚩',
  checkered_flag: '🏁',
  white_flag: '🏳️',
  waving_white_flag: '🏳️',
  black_flag: '🏴',
  waving_black_flag: '🏴',
  crossed_flags: '🎌',
  'rainbow-flag': '🏳️‍🌈',
  rainbow_flag: '🏳️‍🌈',
})
